version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: eshtarek-backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: eshtarek-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=eshtarek
      - POSTGRES_USER=eshtarek_user
      - POSTGRES_PASSWORD=eshtarek_pass

volumes:
  postgres_data:
