name: Django + React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: eshtarek
          POSTGRES_USER: eshtarek_user
          POSTGRES_PASSWORD: eshtarek_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: eshtarek
      POSTGRES_USER: eshtarek_user
      POSTGRES_PASSWORD: eshtarek_pass
      DATABASE_URL: postgres://eshtarek_user:eshtarek_pass@localhost:5432/eshtarek

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Django tests
        working-directory: ./backend
        run: |
          python manage.py migrate
          python manage.py test
